POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content": "VS code rest client is a pre...",
    "important": true
}

###
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content": "#5 note",
    "important": true
}