# Delete a blog by id
DELETE http://localhost:3003/api/blogs/69b363cbe8f7f678e4f414ca
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNjlhODlhNDdjYmY1MzMzN2IzZGJjOWMxIiwiaWF0IjoxNzc0MzkyNDIxLCJleHAiOjE3NzQzOTYwMjF9.aQoCMoJya5QnO4TYTh_FbgroZszBU9kmPmmhVZuqZmc